### ISSUE TITLE
OS check is too strict

### ISSUE THREAD

**Issue by sumseq** [dbkinghorn/nv-gpu-powerlimit-setup#2]
Hi,

This script works on a lot more than Ubuntu - basically anything based on the supported Ubuntu versions.
For example, I use Mint 20.3 and the script works fine (after commenting out the OS check).

Maybe have an OS-check override flag?

 - Ron

**Comment by dbkinghorn** [comment]
I had that in there from earlier code but you are right. I just reviewed this code commit and there really isn't anything in there that is Ubuntu or any derivative specific. In fact it should be OK on any systemd based system (not just debian derived). I could replace the check with a systemd version check.  The sudo check could also be replaced with a uid==0 check too I suppose

I've made a note and will push a change tomorrow. I'll add a comment that I have only tested on Ubuntu > 18.04 but that other distributions should also work.

Thanks! --Don

**Comment by dbkinghorn** [comment]
**Allow non Ubuntu but fail if systemd version is less than 2.37**

- The script should now also run for non Ubuntu/Debian based distros within the last few years (but it's only been tested on Ubuntu!)
- CENTOS 7 will fail because of systemd version 219 but 8 should work
- The systemd check could be commented out in the script if you want to try it on an older distro
